name: CI

env:
  HUGO_ENV: production
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        submodules: true
      - name: Install Hugo
        run: sudo snap install hugo
      - name: Build site
        run: hugo
      - name: Deploy site
        run: hugo deploy
